### ISSUE TITLE
Setting Pump Speed Errors out in HA, though Changes Speed

### ISSUE THREAD

**Issue by N3rdP1um23** [djtimca/haomnilogic#13]
Hey! I was playing around with the pump side of things and was able to follow #9 to add a slider, have it update when the pump updates (through the Omnilogic app or manually using the Pool controller), and have added some automation as well!

However, I've now simulated your "set speed buttons" and when it calls the service, I receive the following error **"Cannot set speed on a non-variable speed pump"** even though a few seconds later I can see that the gauge has changed successfully. 

Before
![image](https://user-images.githubusercontent.com/8093806/172415813-7ae918f0-7dae-436d-ba14-2b24506d890f.png)

After
![image](https://user-images.githubusercontent.com/8093806/172415877-d8dc88b8-6681-49a5-b6e4-589ecbb226f3.png)

As mentioned earlier, the gauge updates (as it's using the value directly from the filter speed sensor and not the number entity) and I've also confirmed in the OmniLogic app that the speed has in fact changed. 

Here's the error that I can see in HAs logs
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/omnilogic/switch.py:235
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:49:04 AM (4 occurrences)
Last logged: 10:58:31 AM

[140039323217200] Cannot set speed on a non-variable speed pump.
[140039998787696] Cannot set speed on a non-variable speed pump.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1704, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1741, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 697, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 964, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/config/custom_components/omnilogic/switch.py", line 235, in async_set_speed
    raise OmniLogicException("Cannot set speed on a non-variable speed pump.")
omnilogic.OmniLogicException: Cannot set speed on a non-variable speed pump.
```

I'm not sure if it's caused by the pump type being not SINGLE as mentioned in the switch code (seen below), or something going out of sync along the way. For reference, here's the pump in use - [TriStar VS 950 Omni](https://www.hayward-pool.ca/shop/ProductDisplay?storeId=11201&urlLangId=-1&productId=4501626&urlRequestType=Base&langId=-1&catalogId=11551)
https://github.com/djtimca/haomnilogic/blob/192561d3e7992799a92699199ee8227727dc6d13/custom_components/omnilogic/switch.py#L214-L235

If there's anything else I can include to help or troubleshoot, just let me know!

**Comment by N3rdP1um23** [comment]
No problem at all! Sure! Below is the requested information! 

```json
[
  {
    "systemId": "REDACTED",
    "statusVersion": "9",
    "airTemp": "67",
    "status": "2",
    "state": "1",
    "configUpdatedTime": "2022-06-06T21:36:05.067Z",
    "datetime": "2022-06-07T14:38:53.976",
    "Relays": [],
    "BOWS": [
      {
        "systemId": "1",
        "flow": "255",
        "waterTemp": "-1",
        "Name": "Pool",
        "Supports-Spillover": "no",
        "Filter": {
          "systemId": "2",
          "valvePosition": "1",
          "filterSpeed": "0",
          "filterState": "0",
          "lastSpeed": "75",
          "Name": "Filter Pump",
          "Shared-Type": "BOW_NO_EQUIPMENT_SHARED",
          "Filter-Type": "FMT_VARIABLE_SPEED_PUMP",
          "Max-Pump-Speed": "100",
          "Min-Pump-Speed": "18",
          "Max-Pump-RPM": "3450",
          "Min-Pump-RPM": "600",
          "Priming-Enabled": "yes",
          "Alarms": []
        },
        "VirtualHeater": {
          "systemId": "3",
          "Current-Set-Point": "75",
          "enable": "yes"
        },
        "Heater": {
          "systemId": "4",
          "heaterState": "0",
          "enable": "yes",
          "Shared-Type": "BOW_NO_EQUIPMENT_SHARED",
          "Operation": {
            "VirtualHeater": {
              "System-Id": "4",
              "Name": "Gas Heater",
              "Type": "PET_HEATER",
              "Heater-Type": "HTR_GAS",
              "Enabled": "yes",
              "Priority": "HTR_PRIORITY_1",
              "Run-For-Priority": "HTR_MAINTAINS_PRIORITY_FOR_AS_LONG_AS_VALID",
              "Shared-Equipment-System-ID": "-1",
              "Current-Set-Point": "75",
              "Max-Water-Temp": "104",
              "Min-Settable-Water-Temp": "55",
              "Max-Settable-Water-Temp": "104",
              "enable": "yes",
              "systemId": "3"
            }
          },
          "Name": "Gas Heater",
          "Alarms": []
        },
        "Chlorinator": {
          "systemId": "9",
          "operatingMode": "1",
          "Timed-Percent": "40",
          "scMode": "0",
          "chlrError": "0",
          "chlrAlert": "2048",
          "avgSaltLevel": "3500",
          "instantSaltLevel": "0",
          "status": "2",
          "Name": "Chlorinator",
          "Shared-Type": "BOW_NO_EQUIPMENT_SHARED",
          "Operation": [
            {
              "System-Id": "10",
              "Name": "Chlorinator1",
              "Type": "PET_CHLORINATOR",
              "Chlorinator-Type": "CHLOR_TYPE_AQUA_RITE",
              "Enabled": "yes"
            }
          ],
          "Alarms": []
        },
        "CSAD": {
          "systemId": "0",
          "ph": "",
          "orp": "",
          "status": "0",
          "mode": "0",
          "Alarms": []
        },
        "Lights": [
          {
            "systemId": "5",
            "lightState": "0",
            "currentShow": "0",
            "Name": "Lights",
            "Type": "COLOR_LOGIC_UCL",
            "V2": "no",
            "Alarms": []
          }
        ],
        "Relays": [],
        "Pumps": [
          {
            "systemId": "6",
            "pumpState": "1",
            "pumpSpeed": "100",
            "lastSpeed": "100",
            "Name": "InFloor Heat",
            "Type": "PMP_SINGLE_SPEED",
            "Function": "PMP_ACCESSORY",
            "Min-Pump-Speed": "18",
            "Max-Pump-Speed": "100",
            "Alarms": []
          }
        ],
        "Heaters": [
          {
            "systemId": "4",
            "heaterState": "0",
            "enable": "yes",
            "Shared-Type": "BOW_NO_EQUIPMENT_SHARED",
            "Operation": {
              "VirtualHeater": {
                "System-Id": "4",
                "Name": "Gas Heater",
                "Type": "PET_HEATER",
                "Heater-Type": "HTR_GAS",
                "Enabled": "yes",
                "Priority": "HTR_PRIORITY_1",
                "Run-For-Priority": "HTR_MAINTAINS_PRIORITY_FOR_AS_LONG_AS_VALID",
                "Shared-Equipment-System-ID": "-1",
                "Current-Set-Point": "75",
                "Max-Water-Temp": "104",
                "Min-Settable-Water-Temp": "55",
                "Max-Settable-Water-Temp": "104",
                "enable": "yes",
                "systemId": "3"
              }
            },
            "Name": "Gas Heater",
            "Alarms": []
          }
        ]
      }
    ],
    "BackyardName": "REDACTED",
    "Msp-Vsp-Speed-Format": "Percent",
    "Msp-Time-Format": "24 Hour Format",
    "Units": "Metric",
    "Msp-Chlor-Display": "Salt",
    "Msp-Language": "English",
    "Unit-of-Measurement": "Metric",
    "Alarms": [
      {
        "BowID": "0",
        "EquipmentID": "10",
        "Resource_Msg_Id": "77",
        "Severity": "1",
        "Parameter1": "Chlorinator1",
        "Parameter2": "none",
        "Valid": "0",
        "Clearable": "1",
        "Message": "CLEAN T-CELL Chlorinator1",
        "Comment": "Cell needs cleaning"
      }
    ],
    "Unit-of-Temperature": "UNITS_FAHRENHEIT"
  }
]
```

My horizontal stack of buttons, looks like this
```yaml
type: horizontal-stack
cards:
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: omnilogic.set_pump_speed
      data:
        speed: 25
      target:
        area_id: pool
        entity_id: switch.pool_filter_pump
    entity: ''
    icon: mdi:speedometer-slow
    hold_action:
      action: none
    name: 25%
    show_state: false
    icon_height: 50px
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: omnilogic.set_pump_speed
      data:
        speed: 50
      target:
        area_id: pool
        entity_id: switch.pool_filter_pump
    entity: ''
    icon: mdi:speedometer-medium
    hold_action:
      action: none
    name: 50%
    show_state: false
    icon_height: 50px
  - show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: omnilogic.set_pump_speed
      data:
        speed: 75
      target:
        area_id: pool
        entity_id: switch.pool_filter_pump
    entity: ''
    icon: mdi:speedometer
    hold_action:
      action: none
    name: 75%
    show_state: false
    icon_height: 50px
```

----

As a side note, for replit, could I make a suggestion or two? Would it be possible to use a hashed version of the username/execution time? Just thinking as the username could be something personal or an email address in some cases.
As an example
```python
import hashlib
from datetime import datetime

file_name_hash = hashlib.sha224(omni_username.encode() + str(datetime.now().timestamp()).encode()).hexdigest()[0:10]
file_name = "output_116_" + file_name_hash + "_telemetry.json"

# f = open("output_116_" + omni_username + "_telemetry.json", "w") ---- previous
f = open(file_name, "w")

print("Your telemetry results can be found in the following file... " + file_name)
```

And last one, zero out or replace the `BackyardName` and `systemId` for similar reasons? May save you from having to clear the files periodically as well haha Just a thought though, no worries at all if not 🙂

**Comment by djtimca** [comment]
@N3rdP1um23 great suggestions on the Replit - I've added the hashing and automatically redact the SystemID and BackyardName now. Thanks!

I'm going to guess that the error is related to having a variable speed filter pump and a single speed pump for infloor heating. For some reason I must be trying to hit both when the service is called. Will do some digging and hopefully have a fix out tomorrow. Thanks!

**Comment by N3rdP1um23** [comment]
Oh, awesome and no problem at all!! :)

Oh yeah, I did notice that, and it did in fact look off haha It's setup as a relay to control a circulation pump (manual on/off at a set schedule). Though now that I'm looking at it more, for some reason it's coming up as another pump from the API 🤔 That's odd lol

**Comment by djtimca** [comment]
I've got an update coming shortly which will require entity_id for the services, but something jumped out at me that might be causing your issue:
```yaml
- show_name: true
    show_icon: true
    type: button
    tap_action:
      action: call-service
      service: omnilogic.set_pump_speed
      data:
        speed: 50
      target:
        area_id: pool
        entity_id: switch.pool_filter_pump
    entity: ''
    icon: mdi:speedometer-medium
    hold_action:
      action: none
    name: 50%
    show_state: false
    icon_height: 50px
```
You have targeted both an `area_id` and `entity_id` on the buttons. I _think_ that both your pumps likely are assigned to the `pool` area, so Home Assistant may be calling the service against both.

Remove the `area_id` from the target section and see if that makes the problem go away.
